// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_stevenf4.Models;

namespace Mission6_stevenf4.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230222182025_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_stevenf4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("categoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            categoryID = 3,
                            director = "Jared Hess",
                            rating = "PG",
                            title = "Nacho Libre",
                            year = 2006
                        },
                        new
                        {
                            MovieID = 2,
                            categoryID = 2,
                            director = "Christopher Nolan",
                            rating = "PG-13",
                            title = "Interstellar",
                            year = 2014
                        },
                        new
                        {
                            MovieID = 3,
                            categoryID = 3,
                            director = "Joel Crawford",
                            rating = "PG",
                            title = "Puss in Boots: The Last Wish",
                            year = 2022
                        });
                });

            modelBuilder.Entity("Mission6_stevenf4.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            categoryName = "Action"
                        },
                        new
                        {
                            categoryID = 2,
                            categoryName = "Adventure"
                        },
                        new
                        {
                            categoryID = 3,
                            categoryName = "Comedy"
                        },
                        new
                        {
                            categoryID = 4,
                            categoryName = "Drama"
                        },
                        new
                        {
                            categoryID = 5,
                            categoryName = "Fantasy"
                        },
                        new
                        {
                            categoryID = 6,
                            categoryName = "Horror"
                        },
                        new
                        {
                            categoryID = 7,
                            categoryName = "Mystery"
                        },
                        new
                        {
                            categoryID = 8,
                            categoryName = "Romance"
                        },
                        new
                        {
                            categoryID = 9,
                            categoryName = "Thriller"
                        });
                });

            modelBuilder.Entity("Mission6_stevenf4.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Mission6_stevenf4.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
