// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_stevenf4.Models;

namespace Mission6_stevenf4.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_stevenf4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            category = "Comedy",
                            director = "Jared Hess",
                            rating = "PG",
                            title = "Nacho Libre",
                            year = 2006
                        },
                        new
                        {
                            MovieID = 2,
                            category = "Adventure",
                            director = "Christopher Nolan",
                            rating = "PG-13",
                            title = "Interstellar",
                            year = 2014
                        },
                        new
                        {
                            MovieID = 3,
                            category = "Comedy",
                            director = "Joel Crawford",
                            rating = "PG",
                            title = "Puss in Boots: The Last Wish",
                            year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
